# Generated by Django 5.2.17 on 2026-08-11 14:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Open Immigration CRM', max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('matter_prefix', models.CharField(default='MAT', max_length=12)),
                ('matter_sequence_year', models.PositiveIntegerField(default=0)),
                ('matter_sequence_value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'firm profile',
            },
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_immigration_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_of_birth', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(blank=True, max_length=80)),
                ('a_number', models.CharField(blank=True, max_length=20, verbose_name='A-number')),
                ('current_immigration_status', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospective client'), ('client', 'Client'), ('former', 'Former client')], db_index=True, default='lead', max_length=20)),
                ('stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('consultation', 'Consultation'), ('retained', 'Retained'), ('active', 'Active matter'), ('closed', 'Closed'), ('lost', 'Not retained')], db_index=True, default='inquiry', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='IntakeInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_invites', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intake_invites', to=settings.AUTH_USER_MODEL)),
                ('intake_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='crm.intakeform')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='crm.intakeinvite')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intake_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matter_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('family', 'Family-based'), ('employment', 'Employment-based'), ('humanitarian', 'Humanitarian'), ('naturalization', 'Naturalization'), ('removal', 'Removal defense'), ('waiver', 'Waiver'), ('appeal', 'Appeal or motion'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=30)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matters', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='crm.contact')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='intakeinvite',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_invites', to='crm.matter'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('immigration', 'Immigration filing'), ('evidence', 'Evidence'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.contact')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_crm_documents', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.matter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='crm.matter')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('status', 'Status change'), ('meeting', 'Meeting'), ('call', 'Call'), ('document', 'Document'), ('intake', 'Intake'), ('system', 'System')], default='note', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.matter')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MatterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_roles', to='crm.contact')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='crm.matter')),
            ],
            options={
                'ordering': ['role', 'contact__last_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('task', 'Task'), ('deadline', 'Deadline'), ('appointment', 'Appointment')], default='task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='crm.contact')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='crm.matter')),
            ],
            options={
                'ordering': ['is_completed', 'scheduled_for', '-priority', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['stage', 'updated_at'], name='crm_contact_stage_9dc769_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['status', 'updated_at'], name='crm_matter_status_bb0a36_idx'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_matter_assigne_ec7a59_idx'),
        ),
        migrations.AddConstraint(
            model_name='matterparty',
            constraint=models.UniqueConstraint(fields=('matter', 'contact', 'role'), name='crm_unique_matter_contact_role'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['is_completed', 'scheduled_for'], name='crm_workite_is_comp_5c9536_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='crm_workite_assigne_874b21_idx'),
        ),
    ]
